//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_RESULTADO_ALUMNO", "ALUMNO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.ALUMNO), "RESULTADO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.RESULTADO), true)]
[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_CURSO_PROFESOR", "PROFESOR", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.PROFESOR), "CURSO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.CURSO), true)]
[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_EXAMEN_CURSO", "CURSO", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.CURSO), "EXAMEN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.EXAMEN), true)]
[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_PREGUNTA_EXAMEN", "EXAMEN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.EXAMEN), "PREGUNTA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.PREGUNTA), true)]
[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_RESULTADO_EXAMEN", "EXAMEN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.EXAMEN), "RESULTADO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.RESULTADO), true)]
[assembly: EdmRelationshipAttribute("ExamenOnLineModel", "FK_RESPUESTA_PREGUNTA", "PREGUNTA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.PREGUNTA), "RESPUESTA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.RESPUESTA), true)]

#endregion

namespace Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ExOnLineEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ExOnLineEntities usando la cadena de conexión encontrada en la sección 'ExOnLineEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ExOnLineEntities() : base("name=ExOnLineEntities", "ExOnLineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ExOnLineEntities.
        /// </summary>
        public ExOnLineEntities(string connectionString) : base(connectionString, "ExOnLineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ExOnLineEntities.
        /// </summary>
        public ExOnLineEntities(EntityConnection connection) : base(connection, "ExOnLineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ALUMNO> Alumnos
        {
            get
            {
                if ((_Alumnos == null))
                {
                    _Alumnos = base.CreateObjectSet<ALUMNO>("Alumnos");
                }
                return _Alumnos;
            }
        }
        private ObjectSet<ALUMNO> _Alumnos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CURSO> Cursos
        {
            get
            {
                if ((_Cursos == null))
                {
                    _Cursos = base.CreateObjectSet<CURSO>("Cursos");
                }
                return _Cursos;
            }
        }
        private ObjectSet<CURSO> _Cursos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EXAMEN> Examenes
        {
            get
            {
                if ((_Examenes == null))
                {
                    _Examenes = base.CreateObjectSet<EXAMEN>("Examenes");
                }
                return _Examenes;
            }
        }
        private ObjectSet<EXAMEN> _Examenes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PREGUNTA> Preguntas
        {
            get
            {
                if ((_Preguntas == null))
                {
                    _Preguntas = base.CreateObjectSet<PREGUNTA>("Preguntas");
                }
                return _Preguntas;
            }
        }
        private ObjectSet<PREGUNTA> _Preguntas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PROFESOR> Profesores
        {
            get
            {
                if ((_Profesores == null))
                {
                    _Profesores = base.CreateObjectSet<PROFESOR>("Profesores");
                }
                return _Profesores;
            }
        }
        private ObjectSet<PROFESOR> _Profesores;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RESPUESTA> Respuestas
        {
            get
            {
                if ((_Respuestas == null))
                {
                    _Respuestas = base.CreateObjectSet<RESPUESTA>("Respuestas");
                }
                return _Respuestas;
            }
        }
        private ObjectSet<RESPUESTA> _Respuestas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RESULTADO> Resultados
        {
            get
            {
                if ((_Resultados == null))
                {
                    _Resultados = base.CreateObjectSet<RESULTADO>("Resultados");
                }
                return _Resultados;
            }
        }
        private ObjectSet<RESULTADO> _Resultados;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumnos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumnos(ALUMNO aLUMNO)
        {
            base.AddObject("Alumnos", aLUMNO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cursos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCursos(CURSO cURSO)
        {
            base.AddObject("Cursos", cURSO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Examenes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToExamenes(EXAMEN eXAMEN)
        {
            base.AddObject("Examenes", eXAMEN);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Preguntas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPreguntas(PREGUNTA pREGUNTA)
        {
            base.AddObject("Preguntas", pREGUNTA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Profesores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProfesores(PROFESOR pROFESOR)
        {
            base.AddObject("Profesores", pROFESOR);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Respuestas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRespuestas(RESPUESTA rESPUESTA)
        {
            base.AddObject("Respuestas", rESPUESTA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Resultados. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToResultados(RESULTADO rESULTADO)
        {
            base.AddObject("Resultados", rESULTADO);
        }

        #endregion

        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="id_Profesor">No hay documentación de metadatos disponible.</param>
        public ObjectResult<ListarCursos_Result> ListarCursos(Nullable<global::System.Int32> id_Profesor)
        {
            ObjectParameter id_ProfesorParameter;
            if (id_Profesor.HasValue)
            {
                id_ProfesorParameter = new ObjectParameter("Id_Profesor", id_Profesor);
            }
            else
            {
                id_ProfesorParameter = new ObjectParameter("Id_Profesor", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ListarCursos_Result>("ListarCursos", id_ProfesorParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="id_Profesor">No hay documentación de metadatos disponible.</param>
        public ObjectResult<ListarExamenes_Result> ListarExamenes(Nullable<global::System.Int32> id_Profesor)
        {
            ObjectParameter id_ProfesorParameter;
            if (id_Profesor.HasValue)
            {
                id_ProfesorParameter = new ObjectParameter("Id_Profesor", id_Profesor);
            }
            else
            {
                id_ProfesorParameter = new ObjectParameter("Id_Profesor", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ListarExamenes_Result>("ListarExamenes", id_ProfesorParameter);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="ALUMNO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ALUMNO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ALUMNO.
        /// </summary>
        /// <param name="idAlumno">Valor inicial de la propiedad IdAlumno.</param>
        public static ALUMNO CreateALUMNO(global::System.Int32 idAlumno)
        {
            ALUMNO aLUMNO = new ALUMNO();
            aLUMNO.IdAlumno = idAlumno;
            return aLUMNO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAlumno
        {
            get
            {
                return _IdAlumno;
            }
            set
            {
                if (_IdAlumno != value)
                {
                    OnIdAlumnoChanging(value);
                    ReportPropertyChanging("IdAlumno");
                    _IdAlumno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdAlumno");
                    OnIdAlumnoChanged();
                }
            }
        }
        private global::System.Int32 _IdAlumno;
        partial void OnIdAlumnoChanging(global::System.Int32 value);
        partial void OnIdAlumnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private Nullable<global::System.Int64> _DNI;
        partial void OnDNIChanging(Nullable<global::System.Int64> value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrasenia
        {
            get
            {
                return _Contrasenia;
            }
            set
            {
                OnContraseniaChanging(value);
                ReportPropertyChanging("Contrasenia");
                _Contrasenia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrasenia");
                OnContraseniaChanged();
            }
        }
        private global::System.String _Contrasenia;
        partial void OnContraseniaChanging(global::System.String value);
        partial void OnContraseniaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESULTADO_ALUMNO", "RESULTADO")]
        public EntityCollection<RESULTADO> RESULTADO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RESULTADO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "RESULTADO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RESULTADO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "RESULTADO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="CURSO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CURSO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CURSO.
        /// </summary>
        /// <param name="idCurso">Valor inicial de la propiedad IdCurso.</param>
        public static CURSO CreateCURSO(global::System.Int32 idCurso)
        {
            CURSO cURSO = new CURSO();
            cURSO.IdCurso = idCurso;
            return cURSO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCurso
        {
            get
            {
                return _IdCurso;
            }
            set
            {
                if (_IdCurso != value)
                {
                    OnIdCursoChanging(value);
                    ReportPropertyChanging("IdCurso");
                    _IdCurso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCurso");
                    OnIdCursoChanged();
                }
            }
        }
        private global::System.Int32 _IdCurso;
        partial void OnIdCursoChanging(global::System.Int32 value);
        partial void OnIdCursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private Nullable<global::System.Int32> _Estado;
        partial void OnEstadoChanging(Nullable<global::System.Int32> value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FecIni
        {
            get
            {
                return _FecIni;
            }
            set
            {
                OnFecIniChanging(value);
                ReportPropertyChanging("FecIni");
                _FecIni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FecIni");
                OnFecIniChanged();
            }
        }
        private Nullable<global::System.DateTime> _FecIni;
        partial void OnFecIniChanging(Nullable<global::System.DateTime> value);
        partial void OnFecIniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FecFin
        {
            get
            {
                return _FecFin;
            }
            set
            {
                OnFecFinChanging(value);
                ReportPropertyChanging("FecFin");
                _FecFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FecFin");
                OnFecFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _FecFin;
        partial void OnFecFinChanging(Nullable<global::System.DateTime> value);
        partial void OnFecFinChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProfId
        {
            get
            {
                return _ProfId;
            }
            set
            {
                OnProfIdChanging(value);
                ReportPropertyChanging("ProfId");
                _ProfId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfId");
                OnProfIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProfId;
        partial void OnProfIdChanging(Nullable<global::System.Int32> value);
        partial void OnProfIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_CURSO_PROFESOR", "PROFESOR")]
        public PROFESOR PROFESOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("ExamenOnLineModel.FK_CURSO_PROFESOR", "PROFESOR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("ExamenOnLineModel.FK_CURSO_PROFESOR", "PROFESOR").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PROFESOR> PROFESORReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("ExamenOnLineModel.FK_CURSO_PROFESOR", "PROFESOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PROFESOR>("ExamenOnLineModel.FK_CURSO_PROFESOR", "PROFESOR", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_EXAMEN_CURSO", "EXAMEN")]
        public EntityCollection<EXAMEN> EXAMEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EXAMEN>("ExamenOnLineModel.FK_EXAMEN_CURSO", "EXAMEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EXAMEN>("ExamenOnLineModel.FK_EXAMEN_CURSO", "EXAMEN", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="EXAMEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EXAMEN : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EXAMEN.
        /// </summary>
        /// <param name="idExamen">Valor inicial de la propiedad IdExamen.</param>
        public static EXAMEN CreateEXAMEN(global::System.Int32 idExamen)
        {
            EXAMEN eXAMEN = new EXAMEN();
            eXAMEN.IdExamen = idExamen;
            return eXAMEN;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdExamen
        {
            get
            {
                return _IdExamen;
            }
            set
            {
                if (_IdExamen != value)
                {
                    OnIdExamenChanging(value);
                    ReportPropertyChanging("IdExamen");
                    _IdExamen = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdExamen");
                    OnIdExamenChanged();
                }
            }
        }
        private global::System.Int32 _IdExamen;
        partial void OnIdExamenChanging(global::System.Int32 value);
        partial void OnIdExamenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Duracion
        {
            get
            {
                return _Duracion;
            }
            set
            {
                OnDuracionChanging(value);
                ReportPropertyChanging("Duracion");
                _Duracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duracion");
                OnDuracionChanged();
            }
        }
        private Nullable<global::System.Int32> _Duracion;
        partial void OnDuracionChanging(Nullable<global::System.Int32> value);
        partial void OnDuracionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FecHora
        {
            get
            {
                return _FecHora;
            }
            set
            {
                OnFecHoraChanging(value);
                ReportPropertyChanging("FecHora");
                _FecHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FecHora");
                OnFecHoraChanged();
            }
        }
        private Nullable<global::System.DateTime> _FecHora;
        partial void OnFecHoraChanging(Nullable<global::System.DateTime> value);
        partial void OnFecHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CursoId
        {
            get
            {
                return _CursoId;
            }
            set
            {
                OnCursoIdChanging(value);
                ReportPropertyChanging("CursoId");
                _CursoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CursoId");
                OnCursoIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CursoId;
        partial void OnCursoIdChanging(Nullable<global::System.Int32> value);
        partial void OnCursoIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_EXAMEN_CURSO", "CURSO")]
        public CURSO CURSO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CURSO>("ExamenOnLineModel.FK_EXAMEN_CURSO", "CURSO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CURSO>("ExamenOnLineModel.FK_EXAMEN_CURSO", "CURSO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CURSO> CURSOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CURSO>("ExamenOnLineModel.FK_EXAMEN_CURSO", "CURSO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CURSO>("ExamenOnLineModel.FK_EXAMEN_CURSO", "CURSO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_PREGUNTA_EXAMEN", "PREGUNTA")]
        public EntityCollection<PREGUNTA> PREGUNTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PREGUNTA>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "PREGUNTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PREGUNTA>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "PREGUNTA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESULTADO_EXAMEN", "RESULTADO")]
        public EntityCollection<RESULTADO> RESULTADO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RESULTADO>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "RESULTADO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RESULTADO>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "RESULTADO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="PREGUNTA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PREGUNTA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PREGUNTA.
        /// </summary>
        /// <param name="idPregunta">Valor inicial de la propiedad IdPregunta.</param>
        /// <param name="examenId">Valor inicial de la propiedad ExamenId.</param>
        public static PREGUNTA CreatePREGUNTA(global::System.Int32 idPregunta, global::System.Int32 examenId)
        {
            PREGUNTA pREGUNTA = new PREGUNTA();
            pREGUNTA.IdPregunta = idPregunta;
            pREGUNTA.ExamenId = examenId;
            return pREGUNTA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPregunta
        {
            get
            {
                return _IdPregunta;
            }
            set
            {
                if (_IdPregunta != value)
                {
                    OnIdPreguntaChanging(value);
                    ReportPropertyChanging("IdPregunta");
                    _IdPregunta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPregunta");
                    OnIdPreguntaChanged();
                }
            }
        }
        private global::System.Int32 _IdPregunta;
        partial void OnIdPreguntaChanging(global::System.Int32 value);
        partial void OnIdPreguntaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamenId
        {
            get
            {
                return _ExamenId;
            }
            set
            {
                OnExamenIdChanging(value);
                ReportPropertyChanging("ExamenId");
                _ExamenId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamenId");
                OnExamenIdChanged();
            }
        }
        private global::System.Int32 _ExamenId;
        partial void OnExamenIdChanging(global::System.Int32 value);
        partial void OnExamenIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_PREGUNTA_EXAMEN", "EXAMEN")]
        public EXAMEN EXAMEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "EXAMEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "EXAMEN").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EXAMEN> EXAMENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "EXAMEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EXAMEN>("ExamenOnLineModel.FK_PREGUNTA_EXAMEN", "EXAMEN", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESPUESTA_PREGUNTA", "RESPUESTA")]
        public EntityCollection<RESPUESTA> RESPUESTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RESPUESTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "RESPUESTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RESPUESTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "RESPUESTA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="PROFESOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PROFESOR : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PROFESOR.
        /// </summary>
        /// <param name="idProfesor">Valor inicial de la propiedad IdProfesor.</param>
        public static PROFESOR CreatePROFESOR(global::System.Int32 idProfesor)
        {
            PROFESOR pROFESOR = new PROFESOR();
            pROFESOR.IdProfesor = idProfesor;
            return pROFESOR;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProfesor
        {
            get
            {
                return _IdProfesor;
            }
            set
            {
                if (_IdProfesor != value)
                {
                    OnIdProfesorChanging(value);
                    ReportPropertyChanging("IdProfesor");
                    _IdProfesor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProfesor");
                    OnIdProfesorChanged();
                }
            }
        }
        private global::System.Int32 _IdProfesor;
        partial void OnIdProfesorChanging(global::System.Int32 value);
        partial void OnIdProfesorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrasenia
        {
            get
            {
                return _Contrasenia;
            }
            set
            {
                OnContraseniaChanging(value);
                ReportPropertyChanging("Contrasenia");
                _Contrasenia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrasenia");
                OnContraseniaChanged();
            }
        }
        private global::System.String _Contrasenia;
        partial void OnContraseniaChanging(global::System.String value);
        partial void OnContraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EsUsuario
        {
            get
            {
                return _EsUsuario;
            }
            set
            {
                OnEsUsuarioChanging(value);
                ReportPropertyChanging("EsUsuario");
                _EsUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsUsuario");
                OnEsUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _EsUsuario;
        partial void OnEsUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnEsUsuarioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_CURSO_PROFESOR", "CURSO")]
        public EntityCollection<CURSO> CURSO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CURSO>("ExamenOnLineModel.FK_CURSO_PROFESOR", "CURSO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CURSO>("ExamenOnLineModel.FK_CURSO_PROFESOR", "CURSO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="RESPUESTA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RESPUESTA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RESPUESTA.
        /// </summary>
        /// <param name="idRespuesta">Valor inicial de la propiedad IdRespuesta.</param>
        /// <param name="preguntaId">Valor inicial de la propiedad PreguntaId.</param>
        public static RESPUESTA CreateRESPUESTA(global::System.Int32 idRespuesta, global::System.Int32 preguntaId)
        {
            RESPUESTA rESPUESTA = new RESPUESTA();
            rESPUESTA.IdRespuesta = idRespuesta;
            rESPUESTA.PreguntaId = preguntaId;
            return rESPUESTA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRespuesta
        {
            get
            {
                return _IdRespuesta;
            }
            set
            {
                if (_IdRespuesta != value)
                {
                    OnIdRespuestaChanging(value);
                    ReportPropertyChanging("IdRespuesta");
                    _IdRespuesta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRespuesta");
                    OnIdRespuestaChanged();
                }
            }
        }
        private global::System.Int32 _IdRespuesta;
        partial void OnIdRespuestaChanging(global::System.Int32 value);
        partial void OnIdRespuestaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EsValida
        {
            get
            {
                return _EsValida;
            }
            set
            {
                OnEsValidaChanging(value);
                ReportPropertyChanging("EsValida");
                _EsValida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsValida");
                OnEsValidaChanged();
            }
        }
        private Nullable<global::System.Int32> _EsValida;
        partial void OnEsValidaChanging(Nullable<global::System.Int32> value);
        partial void OnEsValidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PreguntaId
        {
            get
            {
                return _PreguntaId;
            }
            set
            {
                OnPreguntaIdChanging(value);
                ReportPropertyChanging("PreguntaId");
                _PreguntaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreguntaId");
                OnPreguntaIdChanged();
            }
        }
        private global::System.Int32 _PreguntaId;
        partial void OnPreguntaIdChanging(global::System.Int32 value);
        partial void OnPreguntaIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESPUESTA_PREGUNTA", "PREGUNTA")]
        public PREGUNTA PREGUNTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PREGUNTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "PREGUNTA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PREGUNTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "PREGUNTA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PREGUNTA> PREGUNTAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PREGUNTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "PREGUNTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PREGUNTA>("ExamenOnLineModel.FK_RESPUESTA_PREGUNTA", "PREGUNTA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamenOnLineModel", Name="RESULTADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RESULTADO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RESULTADO.
        /// </summary>
        /// <param name="idResultado">Valor inicial de la propiedad IdResultado.</param>
        /// <param name="alumnoId">Valor inicial de la propiedad AlumnoId.</param>
        /// <param name="examenId">Valor inicial de la propiedad ExamenId.</param>
        public static RESULTADO CreateRESULTADO(global::System.Int32 idResultado, global::System.Int32 alumnoId, global::System.Int32 examenId)
        {
            RESULTADO rESULTADO = new RESULTADO();
            rESULTADO.IdResultado = idResultado;
            rESULTADO.AlumnoId = alumnoId;
            rESULTADO.ExamenId = examenId;
            return rESULTADO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdResultado
        {
            get
            {
                return _IdResultado;
            }
            set
            {
                if (_IdResultado != value)
                {
                    OnIdResultadoChanging(value);
                    ReportPropertyChanging("IdResultado");
                    _IdResultado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdResultado");
                    OnIdResultadoChanged();
                }
            }
        }
        private global::System.Int32 _IdResultado;
        partial void OnIdResultadoChanging(global::System.Int32 value);
        partial void OnIdResultadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FecHora
        {
            get
            {
                return _FecHora;
            }
            set
            {
                OnFecHoraChanging(value);
                ReportPropertyChanging("FecHora");
                _FecHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FecHora");
                OnFecHoraChanged();
            }
        }
        private Nullable<global::System.DateTime> _FecHora;
        partial void OnFecHoraChanging(Nullable<global::System.DateTime> value);
        partial void OnFecHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FecIni
        {
            get
            {
                return _FecIni;
            }
            set
            {
                OnFecIniChanging(value);
                ReportPropertyChanging("FecIni");
                _FecIni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FecIni");
                OnFecIniChanged();
            }
        }
        private Nullable<global::System.DateTime> _FecIni;
        partial void OnFecIniChanging(Nullable<global::System.DateTime> value);
        partial void OnFecIniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Demora
        {
            get
            {
                return _Demora;
            }
            set
            {
                OnDemoraChanging(value);
                ReportPropertyChanging("Demora");
                _Demora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Demora");
                OnDemoraChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Demora;
        partial void OnDemoraChanging(Nullable<global::System.TimeSpan> value);
        partial void OnDemoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Porcentaje
        {
            get
            {
                return _Porcentaje;
            }
            set
            {
                OnPorcentajeChanging(value);
                ReportPropertyChanging("Porcentaje");
                _Porcentaje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Porcentaje");
                OnPorcentajeChanged();
            }
        }
        private Nullable<global::System.Int32> _Porcentaje;
        partial void OnPorcentajeChanging(Nullable<global::System.Int32> value);
        partial void OnPorcentajeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nota
        {
            get
            {
                return _Nota;
            }
            set
            {
                OnNotaChanging(value);
                ReportPropertyChanging("Nota");
                _Nota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nota");
                OnNotaChanged();
            }
        }
        private global::System.String _Nota;
        partial void OnNotaChanging(global::System.String value);
        partial void OnNotaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlumnoId
        {
            get
            {
                return _AlumnoId;
            }
            set
            {
                OnAlumnoIdChanging(value);
                ReportPropertyChanging("AlumnoId");
                _AlumnoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlumnoId");
                OnAlumnoIdChanged();
            }
        }
        private global::System.Int32 _AlumnoId;
        partial void OnAlumnoIdChanging(global::System.Int32 value);
        partial void OnAlumnoIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamenId
        {
            get
            {
                return _ExamenId;
            }
            set
            {
                OnExamenIdChanging(value);
                ReportPropertyChanging("ExamenId");
                _ExamenId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamenId");
                OnExamenIdChanged();
            }
        }
        private global::System.Int32 _ExamenId;
        partial void OnExamenIdChanging(global::System.Int32 value);
        partial void OnExamenIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESULTADO_ALUMNO", "ALUMNO")]
        public ALUMNO ALUMNO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "ALUMNO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "ALUMNO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ALUMNO> ALUMNOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "ALUMNO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ALUMNO>("ExamenOnLineModel.FK_RESULTADO_ALUMNO", "ALUMNO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExamenOnLineModel", "FK_RESULTADO_EXAMEN", "EXAMEN")]
        public EXAMEN EXAMEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "EXAMEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "EXAMEN").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EXAMEN> EXAMENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "EXAMEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EXAMEN>("ExamenOnLineModel.FK_RESULTADO_EXAMEN", "EXAMEN", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ExamenOnLineModel", Name="ListarCursos_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ListarCursos_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CURSOS
        {
            get
            {
                return _CURSOS;
            }
            set
            {
                OnCURSOSChanging(value);
                ReportPropertyChanging("CURSOS");
                _CURSOS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CURSOS");
                OnCURSOSChanged();
            }
        }
        private global::System.String _CURSOS;
        partial void OnCURSOSChanging(global::System.String value);
        partial void OnCURSOSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EXAMEN
        {
            get
            {
                return _EXAMEN;
            }
            set
            {
                OnEXAMENChanging(value);
                ReportPropertyChanging("EXAMEN");
                _EXAMEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EXAMEN");
                OnEXAMENChanged();
            }
        }
        private global::System.String _EXAMEN;
        partial void OnEXAMENChanging(global::System.String value);
        partial void OnEXAMENChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FECHA_Y_HORA
        {
            get
            {
                return _FECHA_Y_HORA;
            }
            set
            {
                OnFECHA_Y_HORAChanging(value);
                ReportPropertyChanging("FECHA_Y_HORA");
                _FECHA_Y_HORA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_Y_HORA");
                OnFECHA_Y_HORAChanged();
            }
        }
        private Nullable<global::System.DateTime> _FECHA_Y_HORA;
        partial void OnFECHA_Y_HORAChanging(Nullable<global::System.DateTime> value);
        partial void OnFECHA_Y_HORAChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ExamenOnLineModel", Name="ListarExamenes_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ListarExamenes_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CURSOS
        {
            get
            {
                return _CURSOS;
            }
            set
            {
                OnCURSOSChanging(value);
                ReportPropertyChanging("CURSOS");
                _CURSOS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CURSOS");
                OnCURSOSChanged();
            }
        }
        private global::System.String _CURSOS;
        partial void OnCURSOSChanging(global::System.String value);
        partial void OnCURSOSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EXAMEN
        {
            get
            {
                return _EXAMEN;
            }
            set
            {
                OnEXAMENChanging(value);
                ReportPropertyChanging("EXAMEN");
                _EXAMEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EXAMEN");
                OnEXAMENChanged();
            }
        }
        private global::System.String _EXAMEN;
        partial void OnEXAMENChanging(global::System.String value);
        partial void OnEXAMENChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FECHA_Y_HORA
        {
            get
            {
                return _FECHA_Y_HORA;
            }
            set
            {
                OnFECHA_Y_HORAChanging(value);
                ReportPropertyChanging("FECHA_Y_HORA");
                _FECHA_Y_HORA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_Y_HORA");
                OnFECHA_Y_HORAChanged();
            }
        }
        private Nullable<global::System.DateTime> _FECHA_Y_HORA;
        partial void OnFECHA_Y_HORAChanging(Nullable<global::System.DateTime> value);
        partial void OnFECHA_Y_HORAChanged();

        #endregion

    }

    #endregion

    
}
